apiVersion: v1
kind: Service
metadata:
  name: svc-postgres-db
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: postgres