apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-postgres-db
  namespace: default
  labels:
    app: postgres
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: pod-postgres-db
      labels:
        app: postgres
    spec:
      containers:
      - name: container-postgres-db
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.database.name }}
        - name: PGDATA
          value: {{ .Values.database.dataPath }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.secretName }}
              key: postgresql-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.secretName }}
              key: postgresql-password
        volumeMounts:
        - name: {{ .Values.volume.name }}
          mountPath: {{ .Values.volume.path }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.volume.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "openebs-hostpath"
      resources:
        requests:
          storage: 1Gi
  serviceName: {{ .Values.service.name }}
