replicaCount: 1

image:
  repository: 10.0.0.20:8082/app
  tag: "v1.0.21"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

database:
  host: "svc-postgres-db"
  port: "5432"
  name: "node"
  secretName: "secret-postgres"