replicaCount: 1

image:
  repository: 10.0.0.20:8082/db
  tag: "v1.0.2"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5432
  name: svc-postgres-db

database:
  name: node
  dataPath: /var/lib/postgresql/data/pgdata
  secretName: secret-postgres

volume:
  name: postgresql-data
  path: /var/lib/postgresql/data