apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-node-app
  namespace: default
  labels:
    app: node
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      name: pod-node-app
      labels:
        app: node
    spec:
      containers:
      - name: container-node-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}