apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-node-app-app
  namespace: default
  labels:
    app: node-app
  # annotations:
    # argocd.argoproj.io/sync-options: Delete=false
spec:
  replicas: {{.Values.replica.count}}
  revisionHistoryLimit: {{.Values.replica.limit}}
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: pod-node-app-app
      labels:
        app: node-app
    spec:
      containers:
        - name: container-node-app-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.service.port}}
          env:
            - name: APPNAME
              value: "app"
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: HOST
              value: "{{ .Values.service.host }}"
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_PORT
              value: "{{ .Values.database.port }}"
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.database.secretName}}
                  key: postgresql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.database.secretName}}
                  key: postgresql-password
