apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-node-app-aiu
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /aiu
            pathType: Prefix
            backend:
              service:
                name: svc-node-app-aiu
                port:
                  number: { { $.Values.service.port } }
